import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        navy: {
          50: "#eef3fb",
          100: "#d9e4f5",
          200: "#b3c8ea",
          300: "#82a5da",
          400: "#4f7dc6",
          500: "#2c5aa8",
          600: "#1d4588",
          700: "#16356b",
          800: "#102752",
          900: "#0a1c3d",
          950: "#06112a",
        },
        crimson: {
          50: "#fdf2f3",
          100: "#fbe3e5",
          200: "#f7c9cc",
          300: "#f0a1a6",
          400: "#e56b73",
          500: "#d63f4b",
          600: "#ba1e2d",
          700: "#a31010",
          800: "#9d0505",
          900: "#7c0f12",
          950: "#3f0608",
        },
        gold: {
          50: "#fdfbf0",
          100: "#f9f3dc",
          200: "#f2e3ae",
          300: "#e8cf77",
          400: "#d9b650",
          500: "#c49a2e",
          600: "#a67c1f",
          700: "#835f18",
          800: "#6b4d15",
          900: "#5a4016",
        },
        yellow: {
          50: "#fdfbf1",
          100: "#f9f3dc",
          200: "#f2e3ae",
          300: "#e8cf77",
          400: "#d9b650",
          500: "#c49a2e",
          600: "#a67c1f",
          700: "#835f18",
          800: "#6b4d15",
          900: "#5a4016",
        },
        amber: {
          50: "#fdf8ef",
          100: "#faedd2",
          200: "#f3dda4",
          300: "#ecc979",
          400: "#e0ae4e",
          500: "#d1952f",
          600: "#b57625",
          700: "#915b1f",
          800: "#77491e",
          900: "#633c1c",
        },
        sky: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-poppins)", "var(--font-inter)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "2px",
        sm: "1px",
        md: "2px",
        lg: "2px",
        xl: "2px",
        "2xl": "2px",
        "3xl": "4px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
